package com.careeros.entity.enums;

public enum EventType {
    JOB_DISCOVERED,
    JOB_SAVED,
    RESUME_SELECTED,
    APPLICATION_SUBMITTED,
    STATUS_CHANGED,
    RECRUITER_CONTACTED,
    ASSESSMENT_COMPLETED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    FOLLOW_UP_SENT,
    OFFER_RECEIVED,
    REJECTION_RECEIVED,
    NOTE
}
